services:
  patchef-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.kube.slc.net/slc/patchef-server
    container_name: patchef-server
    restart: always
    ports:
      - '6970:6970'
    depends_on:
      patchef-database:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - patchef-frontend-network
      - patchef-backend-network

  patchef-database:
    image: postgres:latest
    container_name: patchef-database
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - patchef-database:/var/lib/postgresql/data
    networks:
      - patchef-backend-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  patchef-database:
    name: patchef-database

networks:
  patchef-frontend-network:
    driver: bridge
  patchef-backend-network:
    driver: bridge
