services:
  patchef-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.kube.slc.net/slc/patchef-server
    container_name: patchef-server
    restart: always
    ports:
      - '6970:6970'
    env_file:
      - .env
    networks:
      - patchef-frontend-network
      - patchef-backend-network
    cap_add:
       - SYS_ADMIN
    privileged: true

networks:
  patchef-frontend-network:
    driver: bridge
  patchef-backend-network:
    driver: bridge